In [1]:
! pip install --quiet wbgapi
import matplotlib.pyplot as plt
import wbgapi as wb
import pandas as pd
import numpy as np

In [2]:
paises = ['ATG','ARG','BRB','BLZ','BOL','BRA','CAN','CHL','COL','CRI','CUB','DMA','DOM','ECU','SLV','GRD','GTM','GUY','HTI','HND','JAM','MEX','NIC','PAN','PRY','PER','KN1','LCA','VCT','SUR','BHS','TTO','USA','URY','VEN']

## LIMPIEZA

Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol) (numeric)

In [4]:
# Importación
alcohol= pd.read_csv('Datasets/Alcohol2.csv',
                      sep =';',
                      usecols = ['YEAR (code)','COUNTRY (code)','ALCOHOLTYPE (code)','SA_0000001400 (numeric)'],
                      encoding ='latin-1',
                    )
# Renombrar
alcohol = alcohol.rename({'YEAR (code)'             : 'Year',
                          'COUNTRY (code)'          : 'Country',
                          'ALCOHOLTYPE (code)'      : 'Types' ,
                          'SA_0000001400 (numeric)' : 'Alcohol_pc'
                          }, axis=1)

alcohol = alcohol.drop(alcohol[(alcohol['Types']=='SA_TOTAL')==False].index).drop(['Types'],axis=1)
alcohol = alcohol.pivot(index='Year', columns='Country', values='Alcohol_pc')

# filtro paises
for p in alcohol.columns:
    if ( p in paises ) == False :
        alcohol = alcohol.drop(p,axis=1)                   
    continue
alcohol = alcohol.reset_index()  
alcohol

Country,Year,ARG,ATG,BHS,BLZ,BOL,BRA,BRB,CAN,CHL,...,PAN,PER,PRY,SLV,SUR,TTO,URY,USA,VCT,VEN
0,1990,11.66000,5.14000,12.53000,5.21000,2.89000,5.25000,7.36000,8.77,8.61000,...,5.72000,5.04000,7.55000,2.20000,4.27000,5.97000,7.56000,9.24000,6.18000,8.85000
1,1991,12.32000,4.42000,12.45000,4.91000,3.17000,5.50000,7.54000,8.28,7.99000,...,5.77000,5.26000,9.11000,2.32000,4.38000,6.24000,7.27000,8.71000,6.11000,9.29000
2,1992,12.09000,4.50000,13.20000,5.69000,2.94000,5.27000,7.09000,8.02,7.82000,...,5.50000,5.62000,9.12000,2.17000,4.78000,5.65000,7.24000,8.71000,6.47000,9.47000
3,1993,11.56000,4.30000,12.80000,6.35000,2.97000,4.92000,7.51000,7.50,7.67000,...,5.22000,5.03000,9.85000,2.46000,4.55000,5.18000,7.49000,8.40000,5.97000,9.25000
4,1994,10.94000,4.77000,12.95000,5.55000,3.10000,5.20000,7.39000,7.50,7.73000,...,5.46000,5.28000,9.99000,2.64000,5.21000,5.52000,7.90000,8.25000,5.97000,8.41000
5,1995,10.13000,5.08000,10.93000,5.94000,3.12000,5.89000,5.76000,7.30,8.34000,...,5.55000,5.23000,11.55000,2.77000,4.99000,4.27000,8.15000,8.14000,6.12000,8.24000
6,1996,9.93000,5.44000,10.30000,5.23000,2.98000,5.88000,5.85000,7.40,7.43000,...,5.67000,4.72000,11.05000,2.57000,4.75000,2.40000,7.96000,8.18000,5.74000,8.41000
7,1997,10.25000,5.45000,10.27000,5.16000,3.08000,5.82000,5.88000,7.20,6.57000,...,5.90000,4.62000,10.49000,2.83000,7.21000,3.31000,7.82000,8.10000,5.98000,7.85000
8,1998,9.21000,5.35000,9.78000,5.23000,3.17000,5.74000,5.49000,7.30,7.25000,...,6.28000,4.32000,9.61000,2.79000,7.12000,3.59000,7.81000,8.10000,6.19000,7.77000
9,1999,9.21000,5.65000,8.65000,5.20000,3.67000,5.96000,6.64000,7.50,7.61000,...,6.23000,4.05000,8.29000,3.18000,6.14000,3.81000,7.94000,8.21000,6.73000,7.30000
10,2000,7.67639,6.85711,11.92764,4.69901,2.29779,7.30018,7.31057,NaN,6.23825,...,5.07632,4.75809,5.64014,2.65096,4.45705,4.81164,7.11463,8.21345,5.13103,8.09182
11,2001,7.76367,6.85232,11.37840,4.77362,2.19162,7.17515,7.41672,NaN,6.09690,...,4.89875,4.09404,5.48802,2.76446,4.40578,4.69530,6.90209,8.25130,5.07407,8.15050
12,2002,7.80842,6.67310,10.94389,4.91742,2.24126,7.01962,7.58827,NaN,6.06087,...,4.94005,3.92811,4.80652,2.85009,4.57976,5.24961,6.08416,8.32700,5.21169,6.99431
13,2003,7.61733,6.91212,10.58950,5.63329,2.32374,6.83773,7.51429,NaN,6.37334,...,4.92006,4.58612,4.49117,2.91309,4.70307,5.43753,5.39595,8.40270,5.46903,6.39446
14,2004,7.62589,6.72329,9.60802,6.06803,2.60941,6.70165,7.43078,NaN,6.32132,...,4.97342,4.53756,5.17332,2.78371,4.65687,5.51922,5.87627,8.47840,5.77467,7.58394
15,2005,7.60000,7.43519,9.83115,6.10354,2.80073,6.76236,7.83616,8.00,7.57000,...,4.89555,4.64957,5.50551,2.67848,4.51537,5.75006,6.25881,8.55410,6.37441,7.98235
16,2006,7.80000,7.69522,9.82443,6.28399,3.13356,6.92874,8.11944,8.20,7.33000,...,5.06981,4.47599,5.92494,2.67074,4.56726,6.04769,6.45086,8.62980,6.21877,8.37035
17,2007,8.16000,8.10721,9.92382,6.98788,3.38123,6.91394,8.06611,8.30,7.39000,...,5.45791,4.51375,6.02910,2.73163,4.68752,6.03467,6.51226,8.74335,6.19655,8.89193
18,2008,8.42000,8.40673,9.64775,6.95253,3.51299,6.83191,8.63297,8.40,7.31000,...,5.99996,4.95250,6.88775,2.59359,4.81765,5.98555,6.53667,8.74335,7.17152,8.40862
19,2009,8.34000,7.63684,8.75387,6.44240,3.63668,6.94913,8.24237,8.40,7.67000,...,6.13542,5.03562,6.06075,2.47636,4.92802,5.93229,6.45342,8.66765,6.98341,7.74723
20,2010,8.15000,7.16000,9.21000,6.47000,3.37000,7.16000,8.66000,8.40,7.55000,...,6.10000,5.23000,6.27000,2.30000,5.27000,5.79000,5.99000,8.56000,7.19000,7.40000
21,2011,7.69000,7.24000,9.23000,6.34000,3.30000,7.13000,8.69000,8.20,7.02000,...,6.16000,5.22000,6.14000,2.31000,5.69000,5.79000,6.02000,8.66000,7.04000,6.88000
22,2012,8.00000,8.22000,9.37000,6.35000,3.24000,7.12000,8.90000,8.30,8.35000,...,6.21000,5.35000,5.80000,2.41000,5.79000,5.89000,6.55000,8.85000,6.81000,6.80000
23,2013,8.27000,9.43000,9.23000,6.60000,3.21000,6.86000,9.05000,8.20,7.23000,...,6.21000,5.27000,5.62000,2.35000,5.84000,5.85000,6.42000,8.81000,6.96000,6.84000
24,2014,7.93000,9.66000,9.22000,6.73000,3.17000,6.91000,9.27000,8.10,7.92000,...,6.30000,5.51000,5.39000,2.45000,5.39000,5.90000,6.15000,8.78000,7.12000,6.60000
25,2015,8.49000,9.06000,9.27000,6.71000,3.15000,6.63000,9.68000,8.00,7.89000,...,6.84000,5.68000,5.21000,2.54000,4.75000,5.97000,6.00000,8.78000,7.41000,6.21000
26,2016,8.38000,9.75000,9.30000,6.50000,3.12000,6.37000,10.22000,8.20,7.73000,...,6.61000,5.64000,5.34000,2.64000,5.69000,5.72000,5.53000,8.89000,7.78000,4.13000
27,2017,8.29000,10.78000,9.32000,6.09000,3.05000,6.25000,10.03000,8.10,7.77000,...,6.79000,5.79000,5.49000,2.81000,5.86000,5.58000,5.76000,8.89000,7.81000,3.35000
28,2018,7.95000,11.28000,9.30000,5.95000,3.00000,6.19000,9.99000,8.10,7.80000,...,6.56000,5.74000,5.54000,2.93000,5.97000,5.69000,6.21000,8.93000,7.51000,2.64000
29,2019,7.95000,11.88000,9.48000,5.93000,2.98000,6.12000,9.94000,8.00,7.80000,...,6.54000,5.74000,5.47000,2.94000,6.60000,5.81000,5.42000,8.93000,7.48000,2.51000

In [5]:
# Valores nulos reemplazados con media
alcohol = alcohol.apply(lambda x: x.fillna(x.mean()),axis=0)    

# NOTA: SOLO 'CAN' PRESENTABA 5 VALORES NULO (20=0-2005)

alcohol

Country,Year,ARG,ATG,BHS,BLZ,BOL,BRA,BRB,CAN,CHL,...,PAN,PER,PRY,SLV,SUR,TTO,URY,USA,VCT,VEN
0,1990,11.66000,5.14000,12.53000,5.21000,2.89000,5.25000,7.36000,8.7700,8.61000,...,5.72000,5.04000,7.55000,2.20000,4.27000,5.97000,7.56000,9.24000,6.18000,8.85000
1,1991,12.32000,4.42000,12.45000,4.91000,3.17000,5.50000,7.54000,8.2800,7.99000,...,5.77000,5.26000,9.11000,2.32000,4.38000,6.24000,7.27000,8.71000,6.11000,9.29000
2,1992,12.09000,4.50000,13.20000,5.69000,2.94000,5.27000,7.09000,8.0200,7.82000,...,5.50000,5.62000,9.12000,2.17000,4.78000,5.65000,7.24000,8.71000,6.47000,9.47000
3,1993,11.56000,4.30000,12.80000,6.35000,2.97000,4.92000,7.51000,7.5000,7.67000,...,5.22000,5.03000,9.85000,2.46000,4.55000,5.18000,7.49000,8.40000,5.97000,9.25000
4,1994,10.94000,4.77000,12.95000,5.55000,3.10000,5.20000,7.39000,7.5000,7.73000,...,5.46000,5.28000,9.99000,2.64000,5.21000,5.52000,7.90000,8.25000,5.97000,8.41000
5,1995,10.13000,5.08000,10.93000,5.94000,3.12000,5.89000,5.76000,7.3000,8.34000,...,5.55000,5.23000,11.55000,2.77000,4.99000,4.27000,8.15000,8.14000,6.12000,8.24000
6,1996,9.93000,5.44000,10.30000,5.23000,2.98000,5.88000,5.85000,7.4000,7.43000,...,5.67000,4.72000,11.05000,2.57000,4.75000,2.40000,7.96000,8.18000,5.74000,8.41000
7,1997,10.25000,5.45000,10.27000,5.16000,3.08000,5.82000,5.88000,7.2000,6.57000,...,5.90000,4.62000,10.49000,2.83000,7.21000,3.31000,7.82000,8.10000,5.98000,7.85000
8,1998,9.21000,5.35000,9.78000,5.23000,3.17000,5.74000,5.49000,7.3000,7.25000,...,6.28000,4.32000,9.61000,2.79000,7.12000,3.59000,7.81000,8.10000,6.19000,7.77000
9,1999,9.21000,5.65000,8.65000,5.20000,3.67000,5.96000,6.64000,7.5000,7.61000,...,6.23000,4.05000,8.29000,3.18000,6.14000,3.81000,7.94000,8.21000,6.73000,7.30000
10,2000,7.67639,6.85711,11.92764,4.69901,2.29779,7.30018,7.31057,7.9868,6.23825,...,5.07632,4.75809,5.64014,2.65096,4.45705,4.81164,7.11463,8.21345,5.13103,8.09182
11,2001,7.76367,6.85232,11.37840,4.77362,2.19162,7.17515,7.41672,7.9868,6.09690,...,4.89875,4.09404,5.48802,2.76446,4.40578,4.69530,6.90209,8.25130,5.07407,8.15050
12,2002,7.80842,6.67310,10.94389,4.91742,2.24126,7.01962,7.58827,7.9868,6.06087,...,4.94005,3.92811,4.80652,2.85009,4.57976,5.24961,6.08416,8.32700,5.21169,6.99431
13,2003,7.61733,6.91212,10.58950,5.63329,2.32374,6.83773,7.51429,7.9868,6.37334,...,4.92006,4.58612,4.49117,2.91309,4.70307,5.43753,5.39595,8.40270,5.46903,6.39446
14,2004,7.62589,6.72329,9.60802,6.06803,2.60941,6.70165,7.43078,7.9868,6.32132,...,4.97342,4.53756,5.17332,2.78371,4.65687,5.51922,5.87627,8.47840,5.77467,7.58394
15,2005,7.60000,7.43519,9.83115,6.10354,2.80073,6.76236,7.83616,8.0000,7.57000,...,4.89555,4.64957,5.50551,2.67848,4.51537,5.75006,6.25881,8.55410,6.37441,7.98235
16,2006,7.80000,7.69522,9.82443,6.28399,3.13356,6.92874,8.11944,8.2000,7.33000,...,5.06981,4.47599,5.92494,2.67074,4.56726,6.04769,6.45086,8.62980,6.21877,8.37035
17,2007,8.16000,8.10721,9.92382,6.98788,3.38123,6.91394,8.06611,8.3000,7.39000,...,5.45791,4.51375,6.02910,2.73163,4.68752,6.03467,6.51226,8.74335,6.19655,8.89193
18,2008,8.42000,8.40673,9.64775,6.95253,3.51299,6.83191,8.63297,8.4000,7.31000,...,5.99996,4.95250,6.88775,2.59359,4.81765,5.98555,6.53667,8.74335,7.17152,8.40862
19,2009,8.34000,7.63684,8.75387,6.44240,3.63668,6.94913,8.24237,8.4000,7.67000,...,6.13542,5.03562,6.06075,2.47636,4.92802,5.93229,6.45342,8.66765,6.98341,7.74723
20,2010,8.15000,7.16000,9.21000,6.47000,3.37000,7.16000,8.66000,8.4000,7.55000,...,6.10000,5.23000,6.27000,2.30000,5.27000,5.79000,5.99000,8.56000,7.19000,7.40000
21,2011,7.69000,7.24000,9.23000,6.34000,3.30000,7.13000,8.69000,8.2000,7.02000,...,6.16000,5.22000,6.14000,2.31000,5.69000,5.79000,6.02000,8.66000,7.04000,6.88000
22,2012,8.00000,8.22000,9.37000,6.35000,3.24000,7.12000,8.90000,8.3000,8.35000,...,6.21000,5.35000,5.80000,2.41000,5.79000,5.89000,6.55000,8.85000,6.81000,6.80000
23,2013,8.27000,9.43000,9.23000,6.60000,3.21000,6.86000,9.05000,8.2000,7.23000,...,6.21000,5.27000,5.62000,2.35000,5.84000,5.85000,6.42000,8.81000,6.96000,6.84000
24,2014,7.93000,9.66000,9.22000,6.73000,3.17000,6.91000,9.27000,8.1000,7.92000,...,6.30000,5.51000,5.39000,2.45000,5.39000,5.90000,6.15000,8.78000,7.12000,6.60000
25,2015,8.49000,9.06000,9.27000,6.71000,3.15000,6.63000,9.68000,8.0000,7.89000,...,6.84000,5.68000,5.21000,2.54000,4.75000,5.97000,6.00000,8.78000,7.41000,6.21000
26,2016,8.38000,9.75000,9.30000,6.50000,3.12000,6.37000,10.22000,8.2000,7.73000,...,6.61000,5.64000,5.34000,2.64000,5.69000,5.72000,5.53000,8.89000,7.78000,4.13000
27,2017,8.29000,10.78000,9.32000,6.09000,3.05000,6.25000,10.03000,8.1000,7.77000,...,6.79000,5.79000,5.49000,2.81000,5.86000,5.58000,5.76000,8.89000,7.81000,3.35000
28,2018,7.95000,11.28000,9.30000,5.95000,3.00000,6.19000,9.99000,8.1000,7.80000,...,6.56000,5.74000,5.54000,2.93000,5.97000,5.69000,6.21000,8.93000,7.51000,2.64000
29,2019,7.95000,11.88000,9.48000,5.93000,2.98000,6.12000,9.94000,8.0000,7.80000,...,6.54000,5.74000,5.47000,2.94000,6.60000,5.81000,5.42000,8.93000,7.48000,2.51000

In [6]:
# --- TRATAMIENTO DE VALORES NULOS MEDIANTE FORECAST (MEDIA MOVIL) ----
# años a proyectar (filas)
forecast= 1
for i in range(forecast):
    alcohol.loc[len(alcohol)+i]=[np.nan]*(len(alcohol.columns))
    #obesidad['Year'].loc[len(obesidad)-1]==obesidad.iloc[len(obesidad)-1][0]+1

# Nuevas variables (columnas)
for e in alcohol.columns.drop('Year'):
    alcohol1= alcohol[e].to_frame()
    alcohol1['Year'] = alcohol['Year']
    alcohol[e] = alcohol1[e].rolling(3).mean().shift(forecast)

# Tabla resultado
alcohol = alcohol.drop(range(0,10),axis=0).reset_index( drop=True)
alcohol['Year']=list(range(2000,2021))
alcohol = pd.melt(alcohol, id_vars='Year', value_vars= alcohol.columns[1:],value_name='Alcohol_pc')
alcohol

     Year Country  Alcohol_pc
0    2000     ARG    9.556667
1    2001     ARG    8.698797
2    2002     ARG    8.216687
3    2003     ARG    7.749493
4    2004     ARG    7.729807
..    ...     ...         ...
709  2016     VEN    6.550000
710  2017     VEN    5.646667
711  2018     VEN    4.563333
712  2019     VEN    3.373333
713  2020     VEN    2.833333

[714 rows x 3 columns]

Prevalence of obesity among adults, BMI &GreaterEqual; 30 (age-standardized estimate) (%)

In [7]:
# Importación
obesidad= pd.read_csv('Datasets/Obesidad.csv',
                      sep =';',
                      usecols = ['YEAR (code)','COUNTRY (code)','SEX (code)','NCD_BMI_30A (numeric)'],
                      encoding ='latin-1',
                    )
# Renombrar
obesidad = obesidad.rename({'YEAR (code)'             : 'Year',
                          'COUNTRY (code)'          : 'Country',
                          'SEX (code)'              : 'Both' ,
                          'NCD_BMI_30A (numeric)'   : 'Indice_mc' # Indice de masa corporal
                          }, axis=1)
obesidad = obesidad.drop(obesidad[(obesidad['Both']=='BTSX')==False].index).drop(['Both'],axis=1)
obesidad = obesidad.pivot(index='Year', columns='Country', values='Indice_mc')

# filtro de paises
for p in obesidad.columns:
    if ( p in paises ) == False :
        obesidad = obesidad.drop(p,axis=1)                   
    continue
obesidad = obesidad.reset_index()  


# --- TRATAMIENTO DE VALORES NULOS MEDIANTE FORECAST (MEDIA MOVIL) ----
# años a proyectar (filas)
forecast= 4
for i in range(forecast):
    obesidad.loc[len(obesidad)+i]=[np.nan]*(len(obesidad.columns))
    #obesidad['Year'].loc[len(obesidad)-1]==obesidad.iloc[len(obesidad)-1][0]+1

# Nuevas variables (columnas)
for e in obesidad.columns.drop('Year'):
    obesidad1= obesidad[e].to_frame()
    obesidad1['Year'] = obesidad['Year']
    obesidad[e] = obesidad1[e].rolling(3).mean().shift(forecast)

# Tabla resultado
obesidad = obesidad.drop(range(0,25),axis=0).reset_index( drop=True)
obesidad['Year']=list(range(2000,2021))
obesidad = pd.melt(obesidad, id_vars='Year', value_vars= obesidad.columns[1:],value_name='Indice_mc')
obesidad.columns = ['year','id_pais','obesidad']
obesidad.to_csv('Limpiados/tbl_obesidad.csv')

     Year Country  Indice_mc
0    2000     ARG  18.633333
1    2001     ARG  19.066667
2    2002     ARG  19.500000
3    2003     ARG  19.900000
4    2004     ARG  20.300000
..    ...     ...        ...
709  2016     VEN  23.666667
710  2017     VEN  24.033333
711  2018     VEN  24.400000
712  2019     VEN  24.800000
713  2020     VEN  25.200000

[714 rows x 3 columns]

Estimate of current tobacco use prevalence (%) (age-standardized rate)

In [9]:
# Importación
tabaco= pd.read_csv('C:/Users/yoe_1/Documents/proyecto_grupal/datasets/Tabaco.csv',
                      sep =';',
                      usecols = ['YEAR (code)','COUNTRY (code)','SEX (code)','M_Est_tob_curr_std (numeric)'],
                      encoding ='latin-1',
                    )
# Renombrar
tabaco = tabaco.rename({  'YEAR (code)'                      : 'Year',
                          'COUNTRY (code)'                   : 'Country',
                          'SEX (code)'                       : 'Both' ,
                          'M_Est_tob_curr_std (numeric)'     : 'Tasa_prev' # Tasa de prevalencia
                          }, axis=1)

tabaco = tabaco.drop(tabaco[(tabaco['Both']=='BTSX')==False].index).drop(['Both'],axis=1)
tabaco = tabaco.pivot(index='Year', columns='Country', values='Tasa_prev') 

# filtro de paises
for p in tabaco.columns:
    if ( p in paises ) == False :
        tabaco = tabaco.drop(p,axis=1)                   
    continue
tabaco.reset_index()

Country,Year,ARG,BHS,BLZ,BOL,BRA,BRB,CAN,CHL,COL,...,GUY,HTI,JAM,MEX,PAN,PER,PRY,SLV,URY,USA
0,2000,34.0,10.7,15.0,32.1,23.8,10.2,28.4,46.9,15.1,...,30.2,12.3,17.4,24.0,13.4,32.9,29.1,15.9,35.3,33.8
1,2005,31.5,10.7,13.0,24.9,20.4,9.7,23.3,41.7,13.2,...,24.1,10.9,14.9,20.6,10.5,23.1,23.0,13.4,31.2,30.6
2,2010,28.9,10.7,11.3,19.5,17.4,9.2,19.3,37.1,11.4,...,19.1,9.7,12.8,17.7,8.2,16.3,18.2,11.3,27.5,28.0
3,2015,26.6,10.6,9.7,15.6,14.9,8.8,15.8,32.9,9.9,...,15.1,8.6,11.0,15.2,6.4,11.5,14.5,9.5,24.3,25.3
4,2018,24.9,10.7,8.8,13.2,13.2,8.5,13.6,29.9,8.8,...,12.6,7.9,9.7,13.4,5.3,8.7,12.1,8.3,22.0,23.4
5,2019,24.9,10.7,8.8,13.2,13.2,8.5,13.6,29.9,8.8,...,12.6,7.9,9.7,13.4,5.3,8.7,12.1,8.3,22.0,23.4
6,2020,24.5,10.6,8.5,12.7,12.8,8.5,13.0,29.2,8.5,...,12.1,7.7,9.4,13.1,5.0,8.1,11.5,7.9,21.5,23.0
7,2023,23.3,10.7,7.7,11.3,11.7,6.9,11.6,27.2,7.8,...,10.5,7.2,8.6,11.9,4.4,6.6,10.1,7.2,19.9,18.1
8,2025,22.5,10.7,7.3,10.6,11.0,8.1,10.8,25.9,7.4,...,9.6,6.9,8.1,11.2,3.9,5.7,9.2,6.7,19.0,20.9